version: '3'

services:
  app:
    build:
      context: ./
    image: ruby:3.0
    container_name: app
    volumes:
      - ./:/usr/src/app
    tty: true
    ports:
      - "3000:3000"
    networks:
      - ruby-cc
    depends_on:
      - db

  db:
    image: postgres:11.14
    container_name: db
    volumes:
      - pgdata:/var/lib/postgresql/data:delegated
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    networks:
      - ruby-cc

networks:
  ruby-cc:
    driver: bridge

volumes:
  pgdata:
